Add support to async history update
In order to use react-router together with react-blessed the memory-based history must support async call of listeners.

By default the memory-based history has a sync nature which causes an unexpected behaviour during mount of react components due to a history update that triggers a state change on Router component that was not initialized (https://github.com/rackt/react-router/blob/v1.0.0-rc1/modules/Router.js#L57-L63).

Error message:
TypeError: Cannot read property '_currentElement' of null
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactCompositeComponent.js:551:52)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactCompositeComponent.js:536:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactCompositeComponent.js:465:12)
    at [object Object].wrapper [as updateComponent] (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactCompositeComponent.js:413:12)
    at Object.ReactReconciler.performUpdateIfNecessary (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactReconciler.js:102:22)
    at runBatchedUpdates (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactUpdates.js:129:21)
    at ReactBlessedReconcileTransaction.Mixin.perform (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/nunes/Developer/js/sqlectron/sqlectron-term/node_modules/react/lib/ReactUpdates.js:86:38)